version: "2.1"
services:
  spotweb:
    image: jgeusebroek/spotweb
    container_name: spotweb
    restart: unless-stopped
    environment:
     - PUID=1001
     - GUID=1001
     - TZ=Europe/Warsaw
     - SPOTWEB_DB_TYPE=pdo_mysql
     - SPOTWEB_DB_HOST=spotwebdb
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_NAME=spotweb
     - SPOTWEB_DB_USER=spotweb
     - SPOTWEB_DB_PASS=spotweb
     - "SPOTWEB_CRON_RETRIEVE=* */2 * * *"
    depends_on:
     - spotweb_db
    ports:
     - 80:81
    volumes:
     - /mnt/nvme0/docker/spotweb/spotweb:/config

  spotweb_db:
    image: linuxserver/mariadb
    container_name: spotwebdb
    restart: unless-stopped
    environment:
     - PUID=1001
     - PGID=1001
     - MYSQL_ROOT_PASSWORD=spotweb
     - TZ=Europe/Warsaw
     - MYSQL_DATABASE=spotweb
     - MYSQL_USER=spotweb
     - MYSQL_PASSWORD=spotweb
    volumes:
     - /mnt/nvme0/docker/spotweb/mariadb:/config
    ports:
     - 3306:3306
